
var vegetables = [
  {name: 'Abricot',      img: 'abricot.jpg',       months:[0,0,0,0,0,1,1,1,0,0,0,0],     difficultyRange: 2,     season: 'de juin à août',},
  {name: 'Ail',      img: 'ail.jpg',       months:[1,1,1,1,1,1,1,1,1,1,1,1],     difficultyRange: 1,     season: "toute l'année (pleine saison d'août à décembre)",},
  {name: 'Airelle',      img: 'airelle.jpg',       months:[0,0,0,0,0,0,1,1,0,0,0,0],     difficultyRange: 2,     season: 'de juillet à août',},
  {name: 'Amande',      img: 'amande.jpg',       months:[0,0,0,0,0,0,0,1,1,0,0,0],     difficultyRange: 4,     season: "d'août à septembre",},
  {name: 'Artichaut',      img: 'artichaut.jpg',       months:[0,0,0,1,1,1,1,1,1,0,0,0],     difficultyRange: 2,     season: "d'avril à septembre",},
  {name: 'Asperge blanche',      img: 'asperge-blanche.jpg',       months:[0,0,0,1,1,1,0,0,0,0,0,0],     difficultyRange: 2,     season: "d'avril à juin",},
  {name: 'Asperge verte',      img: 'asperge-verte.jpg',       months:[0,0,0,0,1,1,0,0,0,0,0,0],     difficultyRange: 2,     season: 'en mai et juin',},
  {name: 'Aubergine',      img: 'aubergine.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 1,     season: 'de juin à septembre',},
  {name: 'Bette',      img: 'bette.jpg',       months:[0,0,0,1,1,1,1,1,1,1,0,0],     difficultyRange: 2,     season: "d'avril à octobre",},
  {name: 'Betterave rouge',      img: 'betterave-rouge.jpg',       months:[0,0,0,0,1,1,1,1,1,1,0,0],     difficultyRange: 2,     season: "de mai à octobre",},
  {name: 'Brocoli',      img: 'brocoli.jpg',       months:[1,1,1,1,1,1,1,1,1,1,1,1],     difficultyRange: 1,     season: "toute l'année",},
  {name: 'Carotte',      img: 'carotte.jpg',       months:[1,1,1,0,0,0,0,1,1,1,1,1],     difficultyRange: 1,     season: "d'août à mars",},
  {name: 'Cassis',      img: 'cassis.jpg',       months:[0,0,0,0,0,0,1,1,0,0,0,0],     difficultyRange: 2,     season: 'en juillet et août',},
  {name: 'Catalonia',      img: 'catalonia.jpg',       months:[0,0,0,0,0,0,0,1,1,1,1,1],     difficultyRange: 3,     season: "d'août à décembre",},
  {name: 'Céleri',      img: 'celeri.jpg',       months:[1,1,1,0,0,0,0,0,0,1,1,1],     difficultyRange: 2,     season: "d'octobre à mars",},
  {name: 'Céleri branche',      img: 'celeri-branche.jpg',       months:[1,1,0,0,0,0,0,0,1,1,1,1],     difficultyRange: 2,     season: 'de septembre à février',},
  {name: 'Céleri rave',      img: 'celeri-rave.jpg',       months:[1,1,0,0,0,0,0,0,1,1,1,1],     difficultyRange: 2,     season: 'de septembre à février',},
  {name: 'Cerise',      img: 'cerise.jpg',       months:[0,0,0,0,0,1,0,0,0,0,0,0],     difficultyRange: 4,     season: 'en juin seulement pour la pleine saison (disponible de mai à juillet)',},
  {name: 'Châtaigne',      img: 'chataigne.jpg',       months:[0,0,0,0,0,0,0,0,1,1,1,1],     difficultyRange: 1,     season: 'de septembre à décembre',},
  {name: 'Chou blanc',      img: 'chou-blanc.jpg',       months:[1,1,1,1,0,1,1,1,1,1,1,1],     difficultyRange: 1,     season: "toute l'année",},
  {name: 'Chou de Bruxelles',      img: 'chou-de-bruxelles.jpg',       months:[1,1,1,0,0,0,0,0,1,1,1,1],     difficultyRange: 2,     season: 'de septembre à mars',},
  {name: 'Chou frisé',      img: 'chou-frise.jpg',       months:[1,1,1,0,1,1,1,1,1,1,1,1],     difficultyRange: 1,     season: "toute l'année",},
  {name: 'Chou Romanesco',      img: 'chou-romanesco.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 2,     season: 'de juin à septembre',},
  {name: 'Chou rouge',      img: 'chou-rouge.jpg',       months:[1,1,1,1,0,1,1,1,1,1,1,1],     difficultyRange: 1,     season: "toute l'année",},
  {name: 'Chou-chinois',      img: 'chou-chinois.jpg',       months:[1,1,0,0,1,1,1,1,1,1,1,1],     difficultyRange: 1,     season: "toute l'année",},
  {name: 'Chou-fleur',      img: 'chou-fleur.jpg',       months:[0,0,0,0,1,1,1,1,1,1,0,0],     difficultyRange: 2,     season: 'de mai à octobre',},
  {name: 'Chou-rave',      img: 'chou-rave.jpg',       months:[0,0,1,1,1,1,1,1,1,1,1,0],     difficultyRange: 1,     season: 'de mars à novembre',},
  {name: 'Cima di Rapa',      img: 'cima-di-rapa.jpg',       months:[1,1,1,0,0,0,0,0,0,1,1,1],     difficultyRange: 2,     season: "d'octobre à mars",},
  {name: 'Citron',      img: 'citron.jpg',       months:[1,1,1,0,0,0,0,0,0,0,0,0],     difficultyRange: 3,     season: 'de janvier à mars',},
  {name: 'Citrouille',      img: 'citrouille.jpg',       months:[1,0,0,0,0,0,0,0,0,1,1,1],     difficultyRange: 1,     season: "d'octobre à janvier",},
  {name: 'Clémentine',      img: 'clementine.jpg',       months:[1,1,0,0,0,0,0,0,0,0,1,1],     difficultyRange: 1,     season: 'de novembre à février',},
  {name: 'Coing',      img: 'coing.jpg',       months:[0,0,0,0,0,0,0,0,1,1,0,0],     difficultyRange: 4,     season: 'en septembre et octobre',},
  {name: 'Concombre',      img: 'concombre.jpg',       months:[0,0,0,1,1,1,1,1,1,1,0,0],     difficultyRange: 1,     season: "d'avril à octobre",},
  {name: 'Courge',      img: 'courge.jpg',       months:[1,0,0,0,0,0,0,0,0,1,1,1],     difficultyRange: 1,     season: "d'octobre à janvier",},
  {name: 'Courgette',      img: 'courgette.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 2,     season: 'de juin à septembre',},
  {name: 'Cresson',      img: 'cresson.jpg',       months:[1,0,0,0,0,0,1,1,1,1,1,1],     difficultyRange: 1,     season: 'de juillet à janvier',},
  {name: 'Endive',      img: 'endive.jpg',       months:[1,1,1,1,0,0,0,0,0,1,1,1],     difficultyRange: 1,     season: "d'octobre à avril",},
  {name: 'Epinard',      img: 'epinard.jpg',       months:[1,1,1,1,1,1,0,0,1,1,1,1],     difficultyRange: 1,     season: 'de septembre à juin',},
  {name: 'Fenouil',      img: 'fenouil.jpg',       months:[0,0,0,0,1,1,1,1,1,1,1,1],     difficultyRange: 1,     season: 'de mai à décembre',},
  {name: 'Figue fraîche',      img: 'figue-fraiche.jpg',       months:[0,0,0,0,0,0,0,1,1,1,0,0],     difficultyRange: 3,     season: "d'août à octobre",},
  {name: 'Fraise',      img: 'fraise.jpg',       months:[0,0,0,0,1,1,1,1,0,0,0,0],     difficultyRange: 1,     season: 'de mai à août',},
  {name: 'Framboise',      img: 'framboise.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 1,     season: 'de juin à septembre',},
  {name: 'Groseille',      img: 'groseille.jpg',       months:[0,0,0,0,0,1,1,0,0,0,0,0],     difficultyRange: 2,     season: 'en juin et juillet',},
  {name: 'Haricot',      img: 'haricot.jpg',       months:[0,0,0,0,0,0,1,1,1,1,0,0],     difficultyRange: 1,     season: 'de juillet à octobre',},
  {name: 'Kiwi',      img: 'kiwi.jpg',       months:[1,1,1,1,1,0,0,0,0,0,1,1],     difficultyRange: 1,     season: 'de novembre à mai',},
  {name: 'Laitue romaine',      img: 'laitue-romaine.jpg',       months:[0,0,0,1,1,1,1,1,1,1,0,0],     difficultyRange: 1,     season: "d'avril à octobre",},
  {name: 'Mâche',      img: 'mache.jpg',       months:[1,1,1,1,0,0,0,0,0,1,1,1],     difficultyRange: 1,     season: "d'octobre à avril",},
  {name: 'Maïs',      img: 'mais.jpg',       months:[0,0,0,0,0,0,1,1,1,1,0,0],     difficultyRange: 1,     season: 'de juillet à octobre',},
  {name: 'Mandarine',      img: 'mandarine.jpg',       months:[1,1,1,0,0,0,0,0,0,1,1,1],     difficultyRange: 1,     season: "d'octobre à mars",},
  {name: 'Marron',      img: 'marron.jpg',       months:[0,0,0,0,0,0,0,1,1,1,1,1],     difficultyRange: 1,     season: "d'août à décembre",},
  {name: 'Melon',      img: 'melon.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 1,     season: 'de juin à septembre',},
  {name: 'Mirabelle',      img: 'mirabelle.jpg',       months:[0,0,0,0,0,0,0,1,1,0,0,0],     difficultyRange: 2,     season: 'en août et septembre',},
  {name: 'Mûre',      img: 'mure.jpg',       months:[0,0,0,0,0,0,1,1,1,0,0,0],     difficultyRange: 2,     season: 'de juillet à septembre',},
  {name: 'Myrtille',      img: 'myrtille.jpg',       months:[0,0,0,0,0,0,1,1,1,0,0,0],     difficultyRange: 2,     season: 'de juillet à septembre',},
  {name: 'Navet',      img: 'navet.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 2,     season: 'de juin à septembre',},
  {name: 'Nectarine',      img: 'nectarine.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 1,     season: 'de juin à septembre',},
  {name: 'Noisette',      img: 'noisette.jpg',       months:[0,0,0,0,0,0,0,1,1,1,0,0],     difficultyRange: 3,     season: "d'août à octobre",},
  {name: 'Noix',      img: 'noix.jpg',       months:[0,0,0,0,0,0,0,0,1,1,1,0],     difficultyRange: 3,     season: 'de septembre à novembre',},
  {name: 'Oignon',      img: 'oignon.jpg',       months:[1,1,1,1,0,0,0,0,1,1,1,1],     difficultyRange: 1,     season: 'de septembre à avril',},
  {name: 'Orange',      img: 'orange.jpg',       months:[1,1,0,0,0,0,0,0,0,0,1,1],     difficultyRange: 1,     season: 'de novembre à février',},
  {name: 'Pamplemousse',      img: 'pamplemousse.jpg',       months:[1,1,1,0,0,0,0,0,0,0,0,1],     difficultyRange: 2,     season: 'de décembre à mars',},
  {name: 'Panais',      img: 'panais.jpg',       months:[1,1,1,0,0,0,0,0,1,1,1,1],     difficultyRange: 2,     season: 'de septembre à mars',},
  {name: 'Pastèque',      img: 'pasteque.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 1,     season: 'de juin à septembre',},
  {name: 'Pâtisson',      img: 'patisson.jpg',       months:[0,0,0,0,0,0,1,1,1,0,0,0],     difficultyRange: 4,     season: 'de juillet à septembre',},
  {name: 'Pêche',      img: 'peche.jpg',       months:[0,0,0,0,0,1,1,1,1,0,0,0],     difficultyRange: 1,     season: 'de juin à septembre',},
  {name: 'Petit oignon blanc',      img: 'petit-oignon-blanc.jpg',       months:[0,0,1,1,1,1,1,1,1,1,0,0],     difficultyRange: 1,     season: 'de mars à octobre',},
  {name: 'Petit pois',      img: 'petit-pois.jpg',       months:[0,0,0,0,1,1,0,0,0,0,0,0],     difficultyRange: 4,     season: 'en mai et juin',},
  {name: 'Poire',      img: 'poire.jpg',       months:[1,0,0,0,0,0,0,1,1,1,1,1],     difficultyRange: 1,     season: "d'août à janvier",},
  {name: 'Poireau',      img: 'poireau.jpg',       months:[1,1,1,1,0,0,0,0,1,1,1,1],     difficultyRange: 1,     season: 'de septembre à avril',},
  {name: 'Pois mange-tout',      img: 'pois-mange-tout.jpg',       months:[0,0,0,0,0,1,1,0,0,0,0,0],     difficultyRange: 4,     season: 'en juin et juillet',},
  {name: 'Poivron',      img: 'poivron.jpg',       months:[0,0,0,0,0,1,1,1,1,1,0,0],     difficultyRange: 1,     season: 'de juin à octobre',},
  {name: 'Pomme',      img: 'pomme.jpg',       months:[1,1,1,0,0,0,0,0,0,1,1,1],     difficultyRange: 1,     season: "d'octobre à mars",},
  {name: 'Pomme de terre',      img: 'pomme-de-terre.jpg',       months:[1,1,0,0,1,1,1,1,1,1,1,1],     difficultyRange: 1,     season: "toute l'année",},
  {name: 'Potimarron',      img: 'potimarron.jpg',       months:[1,0,0,0,0,0,0,0,0,1,1,1],     difficultyRange: 2,     season: "d'octobre à janvier",},
  {name: 'Potiron',      img: 'potiron.jpg',       months:[0,0,0,0,0,0,1,1,1,1,0,0],     difficultyRange: 2,     season: 'de juillet à octobre',},
  {name: 'Prune',      img: 'prune.jpg',       months:[0,0,0,0,0,0,0,1,1,1,0,0],     difficultyRange: 3,     season: "d'août à octobre",},
  {name: 'Quetsche',      img: 'quetsche.jpg',       months:[0,0,0,0,0,0,0,1,1,1,0,0],     difficultyRange: 3,     season: "d'août à octobre",},
  {name: 'Radis',      img: 'radis.jpg',       months:[0,0,1,1,1,1,0,0,0,0,0,0],     difficultyRange: 2,     season: 'de mars à juin',},
  {name: 'Radis long',      img: 'radis-long.jpg',       months:[0,0,0,0,1,1,1,1,0,0,0,0],     difficultyRange: 2,     season: 'de mai à août',},
  {name: 'Raisin',      img: 'raisin.jpg',       months:[0,0,0,0,0,0,0,0,1,1,0,0],     difficultyRange: 2,     season: 'en septembre et octobre',},
  {name: 'Reine-claude',      img: 'reine-claude.jpg',       months:[0,0,0,0,0,0,0,1,1,0,0,0],     difficultyRange: 4,     season: 'en août et septembre',},
  {name: 'Rhubarbe',      img: 'rhubarbe.jpg',       months:[0,0,0,1,1,1,1,0,0,0,0,0],     difficultyRange: 2,     season: "d'avril à juillet",},
  {name: 'Salsifis',      img: 'salsifis.jpg',       months:[1,1,1,0,0,0,0,0,0,1,1,1],     difficultyRange: 2,     season: "d'octobre à mars",},
  {name: 'Tomate',      img: 'tomate.jpg',       months:[0,0,0,0,1,1,1,1,1,0,0,0],     difficultyRange: 1,     season: 'de mai à septembre',},
  {name: 'Topinambour',      img: 'topinambour.jpg',       months:[1,1,0,0,0,0,0,0,0,1,1,1],     difficultyRange: 2,     season: "d'octobre à février",},
];

var win = ["T'es trop fort","Tu cartonnes","Youpi","Yallah!","Bravo !","T'es une star","Amaaaziiing!","C'est tout bon !","Super !","Excellent !","Hip hip hip hourraaaAA !"];

var lose = ["Aïe","Dommage","Il va falloir réviser un peu...","Non, non, non !","C'est pas ça","Raté","Tu peux mieux faire !","Essaie encore !", "On y croit, tu vas y arriver", "Oups", "Continue à t'entraîner"];

var scoreGradeMessage = ["Il va falloir réviser","Bon début, encore des progrès à faire, on y croit !","Bien, bien, tu connais ton sujet !","Waouh ! T'es une super star, tu m'invites quand à dîner ?"];
